// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWCi07mXuDcUWqe2HBSkYLkr7gpTN30ZQ',
    appId: '1:865994733499:web:10eedb90c04c1175c6769e',
    messagingSenderId: '865994733499',
    projectId: 'nutricare-1fb2c',
    authDomain: 'nutricare-1fb2c.firebaseapp.com',
    storageBucket: 'nutricare-1fb2c.firebasestorage.app',
    measurementId: 'G-X8JBEZ0917',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT7_elmiAXTTKKIfVhHer0jA9zHlCsHVo',
    appId: '1:865994733499:android:3085d261c36b3e32c6769e',
    messagingSenderId: '865994733499',
    projectId: 'nutricare-1fb2c',
    storageBucket: 'nutricare-1fb2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBthq6EXCVf_5BjCGz9kJE4ZS_goTIxLmM',
    appId: '1:865994733499:ios:ebffd0f2b996051ac6769e',
    messagingSenderId: '865994733499',
    projectId: 'nutricare-1fb2c',
    storageBucket: 'nutricare-1fb2c.firebasestorage.app',
    iosBundleId: 'com.example.nutricareMvp',
  );
}
