import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'screens/home_dashboard_clean.dart';
import 'screens/food_log.dart';
import 'screens/chat_page.dart';
import 'screens/profile_page.dart';
import 'screens/login.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:fluttertoast/fluttertoast.dart';

// IMPORTANT: `firebase_options.dart` is generated by the FlutterFire CLI.
// You must run `flutterfire configure` locally (see README below) which will
// create `lib/firebase_options.dart`. The app will attempt to initialize
// Firebase and will show an informative message if the file/config is missing.
import 'firebase_options.dart' as firebase_options;


void main() async {
        WidgetsFlutterBinding.ensureInitialized();
            try {
                await Firebase.initializeApp(
                    options: firebase_options.DefaultFirebaseOptions.currentPlatform,
                );
            } catch (e) {
                // If firebase_options.dart is missing or initialization fails we still
                // continue but show a toast so the developer knows to configure Firebase.
                Fluttertoast.showToast(msg: 'Firebase initialization warning: $e');
            }

        runApp(const NutriCareApp());
}

class NutriCareApp extends StatelessWidget {
    const NutriCareApp({Key? key}) : super(key: key);

    @override
    Widget build(BuildContext context) {
                                                                                                // Build a Material 3 fitness-focused ThemeData using a teal-green
                                                                                                // seed color. We keep merged GoogleFonts for wide glyph coverage
                                                                                                // but override key text styles and component themes to match the
                                                                                                // requested design.
                                                                                                final base = ThemeData.light();
                                                                                                final poppins = GoogleFonts.poppinsTextTheme(base.textTheme);
                                                                                                final noto = GoogleFonts.notoSansTextTheme(base.textTheme);
                                                                                                final mergedTextTheme = poppins.merge(noto);

                                                                                                const seed = Color(0xFF00BFA5);
                                                                                                final colorScheme = ColorScheme.fromSeed(seedColor: seed, brightness: Brightness.light);

                                                                                                final textTheme = mergedTextTheme.copyWith(
                                                                                                    headlineLarge: TextStyle(fontWeight: FontWeight.bold, color: colorScheme.onSurface.withOpacity(0.87)),
                                                                                                    titleMedium: TextStyle(fontWeight: FontWeight.w600, color: colorScheme.onSurface.withOpacity(0.87)),
                                                                                                    bodyMedium: TextStyle(color: colorScheme.onSurface.withOpacity(0.7), fontSize: 15),
                                                                                                );

                                                                                                final appTheme = ThemeData(
                                                                                                    useMaterial3: true,
                                                                                                    colorScheme: colorScheme,
                                                                                                    scaffoldBackgroundColor: const Color(0xFFF7F9FC),
                                                                                                    textTheme: textTheme,
                                                                                                    fontFamily: 'NotoSans',
                                                                                                    visualDensity: VisualDensity.adaptivePlatformDensity,
                                                                                                    elevatedButtonTheme: ElevatedButtonThemeData(
                                                                                                        style: ElevatedButton.styleFrom(
                                                                                                            backgroundColor: colorScheme.primary,
                                                                                                            foregroundColor: colorScheme.onPrimary,
                                                                                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                                                                                                            padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 20),
                                                                                                            textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                                                                                                        ),
                                                                                                                                        ),
                                                                                                                                    filledButtonTheme: FilledButtonThemeData(
                                                                                                                                        style: FilledButton.styleFrom(
                                                                                                                                            backgroundColor: colorScheme.primary,
                                                                                                                                            foregroundColor: colorScheme.onPrimary,
                                                                                                                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                                                                                                                                            padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 20),
                                                                                                                                            textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
                                                                                                                                        ),
                                                                                                                                    ),
                                                                                                                                                                            cardTheme: CardThemeData(
                                                                                                                                                                                color: colorScheme.surface,
                                                                                                                                                                                elevation: 3,
                                                                                                                                                                                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
                                                                                                                                                                                margin: const EdgeInsets.all(12),
                                                                                                                                                                            ),
                                                                                                    appBarTheme: AppBarTheme(
                                                                                                        backgroundColor: colorScheme.primary,
                                                                                                        foregroundColor: colorScheme.onPrimary,
                                                                                                        elevation: 0,
                                                                                                        centerTitle: true,
                                                                                                        titleTextStyle: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: colorScheme.onPrimary),
                                                                                                    ),
                                                                                                    pageTransitionsTheme: const PageTransitionsTheme(builders: {
                                                                                                        TargetPlatform.android: FadeUpwardsPageTransitionsBuilder(),
                                                                                                        TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
                                                                                                        TargetPlatform.windows: FadeUpwardsPageTransitionsBuilder(),
                                                                                                    }),
                                                                                                );

                                                                                                        return MaterialApp(
                                                                                                    debugShowCheckedModeBanner: false,
                                                                                                    title: 'NutriCare',
                                                                                                    theme: appTheme,
                                                                                                                                // The app shows login if user isn't authenticated.
                                                                                                                                home: StreamBuilder<User?>(
                                                                                                                                    stream: FirebaseAuth.instance.authStateChanges(),
                                                                                                                                    builder: (context, snapshot) {
                                                                                                                                        if (snapshot.connectionState == ConnectionState.waiting) {
                                                                                                                                            return const Scaffold(body: Center(child: CircularProgressIndicator()));
                                                                                                                                        }
                                                                                                                                        final user = snapshot.data;
                                                                                                                                        if (user == null) return const LoginPage();
                                                                                                                                        return const HomeDashboard();
                                                                                                                                    },
                                                                                                                                ),
                                                                                                                                routes: {
                                                                                                                                    '/dashboard': (context) => const HomeDashboard(),
                                                                                                                                    '/log': (context) => const FoodLog(),
                                                                                                                                    '/chat': (context) => const ChatPage(),
                                                                                                                                    '/profile': (context) => const ProfilePage(),
                                                                                                                                    '/login': (context) => const LoginPage(),
                                                                                                                                },
                );
    }
}
